sql:
  default: 'postgre'
  postgre:
    lib: 'psycopg2'
    args: []
    kwargs:
      host: 'fhir-pipe-mimic-db'
      port: 5432
      database: 'mimic'
      user: 'mimicuser'
      password: 'mimicuser'
fhirstore:
  host: 'mongo'
  port: 27017
  database: 'fhirstore'
  user: 'admin'
  password: 'admin'

graphql:
  server: 'https://graphql.pyrog.staging.arkhn.org/'
  token: '<token>'
