sql:
  default: "postgres"
  postgres:
    lib: "psycopg2"
    args: []
    kwargs:
      host: "localhost"
      port: 5431
      database: "mimic"
      user: "mimicuser"
      password: "mimicuser"
  oracle:
    lib: "cx_Oracle"
    args: ["user/password@database"]
    kwargs: {}

fhirstore:
  host: "localhost"
  port: 27017
  database: "fhirstore"
  user: null
  password: null

graphql:
  server: "https://graphql.pyrog.staging.arkhn.org/"
  token: "<token>"

logging:
  filename: fhirpipe.log
