sql:
  default: 'postgre'
  postgre:
    lib: 'psycopg2'
    args: []
    kwargs:
      host: 'localhost'
      port: 5431
      database: 'mimic'
      user: 'mimicuser'
      password: 'mimicuser'
fhirstore:
  host: 'localhost'
  port: 27017
  database: 'fhirstore'
  user: ''
  password: ''

graphql:
  server: 'https://graphql.pyrog.staging.arkhn.org/'
  token: '<token>'
