version: '3.7'
services:
  arkhn-pipe-mimic:
    build:
      context: .
    container_name: fhir-pipe
    image: arkhn/fhir-pipe:latest
    command: fhirpipe-run --config=/app/fhirpipe/config_docker.yml --project=Mimic
    # command: tail -F anything
    depends_on:
      - fhirbase

  fhirbase:
    image: fhirbase/fhirbase:latest
    container_name: fhir-pipe-fhirbase
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '3000:3000'
      - '5433:5432'

volumes:
  mimic-db:
    name: fhir-pipe-mimic-db
