version: '3.7'
services:
  fhir-pipe:
    name: fhir-pipe
    build:
      context: .
    image: arkhn/fhir-pipe:latest
    command: tail -F anything
    volumes:
      - ./test:/app/test
    depends_on:
      - mimic-db

  mimic-db:
    env_file: .env
    build:
      context: ./docker
      dockerfile: MimicPSQL.Dockerfile
      args:
        MIMIC_USER: $MIMIC_USER
        MIMIC_PASSWORD: $MIMIC_PASSWORD
    container_name: fhir-pipe-mimic-db
    restart: always
    environment:
      POSTGRES_USER: mimicuser
      POSTGRES_PASSWORD: mimicuser
      POSTGRES_DB: mimic
    volumes:
      - mimic-db:/var/lib/postgresql/data
    ports:
      - '5431:5432'

volumes:
  mimic-db:
    name: fhir-pipe-mimic-db
  fhirstore-db:
