version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: mockdb
      POSTGRES_PASSWORD: mockdb
      POSTGRES_DB: mockdb
    volumes:
      - ./docker-test-config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-test-config/csvs:/var/lib/postgresql/csvs


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fhirstore
    ports:
      - 27017:27017

volumes:
  postgres:
