version: "3.7"
services:
  fhir-pipe:
    image: arkhn/fhir-pipe:latest
    container_name: fhir-pipe
    build:
      context: .
    volumes:
      - ./test:/app/test
    ports:
      - "5003:5003"
    depends_on:
      - mimic

  mimic:
    image: arkhn/mimic:latest
    container_name: mimic
    env_file: .env
    build:
      context: ./docker
      dockerfile: MimicPSQL.Dockerfile
      args:
        MIMIC_USER: $MIMIC_USER
        MIMIC_PASSWORD: $MIMIC_PASSWORD
    restart: always
    environment:
      POSTGRES_USER: mimicuser
      POSTGRES_PASSWORD: mimicuser
      POSTGRES_DB: mimic
    volumes:
      - mimic-db:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fhirstore
    ports:
      - 27017:27017
    volumes:
      - fhirstore-db:/data/db

volumes:
  mimic-db:
    name: mimic-db
  fhirstore-db:
